# Generated by Django 4.1.6 on 2023-03-15 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vender_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vender_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Provider',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_image', models.ImageField(upload_to='VenueImage')),
                ('mobile', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('veg_price', models.IntegerField()),
                ('nonveg_price', models.IntegerField()),
                ('room_availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Wishlist',
            fields=[
                ('venuewl_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venue_provider')),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Rating',
            fields=[
                ('venuerating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('reviews', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='Rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venue_provider')),
            ],
        ),
        migrations.AddField(
            model_name='venue_provider',
            name='Venue_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venue_type'),
        ),
        migrations.CreateModel(
            name='Venue_Cart',
            fields=[
                ('venuecart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venue_provider')),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Booking',
            fields=[
                ('venueb_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venue_provider')),
            ],
        ),
        migrations.CreateModel(
            name='Venders',
            fields=[
                ('vender_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vender_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('vender_image', models.ImageField(upload_to='VenderImage')),
                ('price', models.CharField(max_length=5)),
                ('vender_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.vender_type')),
            ],
        ),
        migrations.CreateModel(
            name='Vender_Wishlist',
            fields=[
                ('venderwl_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venders')),
            ],
        ),
        migrations.CreateModel(
            name='Vender_Rating',
            fields=[
                ('venderrating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('reviews', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='Rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venders')),
            ],
        ),
        migrations.CreateModel(
            name='Vender_Cart',
            fields=[
                ('vendercart_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venders')),
            ],
        ),
        migrations.CreateModel(
            name='Vender_Booking',
            fields=[
                ('venderb_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venders')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(upload_to='ProfileImage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
