# Generated by Django 4.1.6 on 2023-03-16 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vender_booking',
            options={'ordering': ['-orderdate']},
        ),
        migrations.AlterField(
            model_name='vender_rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Rating'),
        ),
        migrations.AlterField(
            model_name='vender_rating',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
