# Generated by Django 4.1.6 on 2023-03-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_alter_vender_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vender_rating',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterModelOptions(
            name='vender_type',
            options={'ordering': ['vender_type']},
        ),
        migrations.AlterModelOptions(
            name='venders',
            options={'ordering': ['vender_type']},
        ),
        migrations.AlterModelOptions(
            name='venue_provider',
            options={'ordering': ['-Venue_Type']},
        ),
    ]
