# Generated by Django 4.1.6 on 2023-03-20 16:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tables', '0003_alter_vender_rating_options_and_more'),
        ('Cake', '0002_alter_cake_provider_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MANAGER',
            fields=[
                ('manager_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(default='7970656807', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('email', models.EmailField(default='@gmail.com', max_length=254, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(50)])),
                ('state', models.CharField(default='Madhya Pradesh', max_length=20)),
                ('city', models.CharField(default='Bhopal', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='MANAGER_VENUE_BOOKING',
            fields=[
                ('mbooking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venue_provider')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='MANAGER_VENDER_BOOKING',
            fields=[
                ('mbooking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.venders')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='MANAGER_CAKE_BOOKING',
            fields=[
                ('mbooking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cake.cake')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
