# Generated by Django 4.1.6 on 2023-03-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_manager_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_vender_booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
