# Generated by Django 4.1.7 on 2023-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_alter_manager_vender_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(default='', upload_to='Profile'),
        ),
        migrations.AddField(
            model_name='manager',
            name='price',
            field=models.IntegerField(default='10000'),
        ),
    ]
