# Generated by Django 4.1.7 on 2023-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_manager_image_manager_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_booking',
            name='cake',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
        migrations.AddField(
            model_name='manager_booking',
            name='makeup',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
        migrations.AddField(
            model_name='manager_booking',
            name='mehndi',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
        migrations.AddField(
            model_name='manager_booking',
            name='photographer',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
