# Generated by Django 4.1.7 on 2023-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_manager_booking_cake_manager_booking_makeup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_booking',
            name='cake',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manager_booking',
            name='makeup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manager_booking',
            name='mehndi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manager_booking',
            name='photographer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
