# Generated by Django 4.1.7 on 2023-04-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0007_alter_manager_booking_cake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_booking',
            name='cake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager_booking',
            name='makeup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager_booking',
            name='mehndi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager_booking',
            name='photographer',
            field=models.BooleanField(default=False),
        ),
    ]
